service: carbdash-server

configValidationMode: error
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

custom:
  photoBucket: sustainabyte-photos
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 5

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  timeout: 15
  environment:
    AUTH0_CLIENT_ID: ${file(./secrets.json):AUTH0_CLIENT_ID}
    AUTH0_CLIENT_PUBLIC_KEY: ${file(./public_key)}
    MONGODB_URL: ${file(./secrets.json):MONGODB_URL}
    S3_BUCKET_POSTS: ${self:custom.photoBucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - S3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.photoBucket}/*"

functions:
  - ${file(src/functions/lambdaAuth/functions.yml)}
  - ${file(src/functions/challenge/functions.yml)}
  - ${file(src/functions/checkIn/functions.yml)}
  - ${file(src/functions/offer/functions.yml)}
  - ${file(src/functions/post/functions.yml)}
  - ${file(src/functions/restaurant/functions.yml)}
  - ${file(src/functions/review/functions.yml)}
  - ${file(src/functions/socialGroup/functions.yml)}
  - ${file(src/functions/user/functions.yml)}
  - ${file(src/functions/recent/functions.yml)}
  - ${file(src/functions/follow/functions.yml)}
  - ${file(src/functions/save/functions.yml)}
  - ${file(src/functions/auth/functions.yml)}
  - ${file(src/functions/image/functions.yml)}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
