service: carbdash-server

configValidationMode: error
variablesResolutionMode: 20210326

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  prune:
    automatic: true
    number: 5

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  lambdaHashingVersion: 20201221
  environment:
    AUTH0_CLIENT_ID: ${file(./secrets.json):AUTH0_CLIENT_ID}
    AUTH0_CLIENT_PUBLIC_KEY: ${file(./public_key)}
    MONGODB_URL: ${file(./secrets.json):MONGODB_URL}

functions:
  - ${file(src/functions/lambdaAuth/functions.yml)}
  - ${file(src/functions/user/functions.yml)}
  - ${file(src/functions/restaurant/functions.yml)}
  - ${file(src/functions/review/functions.yml)}
